arb-dir: lib/l10n
template-arb-file: ios_human_interface_en.arb
output-localization-file: ios_human_interface_localizations.dart
output-class: IosHumanInterfaceLocalizations
nullable-getter: false
synthetic-package: false